stages:
  - build

build-apk:
  stage: build
  image:
    name: registry.gitlab.com/les-connecteurs/docker/alpine-buildrepo
    entrypoint: [""]
  script:
    - cd /home/builder
    - cp -r --no-preserve=mode,ownership "$CI_PROJECT_DIR" aports
    - ./entrypoint.sh main
    - ls packages
  only:
    - master
