stages:
  - build

build-apk:
  stage: build
  image:
    name: registry.gitlab.com/les-connecteurs/docker/alpine-buildrepo
    entrypoint: [""]
  script:
    - cd /home/builder
    - sudo cp -r "$CI_PROJECT_DIR" aports
    - sudo chown -R builder:builder aports
    - sudo -u builder ./entrypoint.sh main
    - chmod +x aport/directory_index.sh
    - aport/directory_index.sh packages
  only:
    - master
